### ISSUE TITLE
Scoreboard probleem

### ISSUE THREAD

**Issue by sanderdevaan** [RKMP/RKMP-Premium-ISSUES#1]
Hallo
Om de hoeveelheid seconde knippert het scoreboard bij mij. Ik gebruik de plugin op 1.8 en maak gebruik van ViaVersion.

Ook wil ik vragen of het mogelijk is het automatisch loon zelf te bepalen naar een geschikt bedrag.

Groeten Sander

**Comment by Rammelkast** [comment]
Dit komt door te weinig CPU-kracht van de server, of doordat er te weinig RAM vrij is.
Ik raad je aan om het type processor bij je host te vragen en te vragen of ze hier iets aan kunnen doen,

Een tijdelijke oplossing zal binnenkort uit moeten komen.

**Comment by sanderdevaan** [comment]
Bedankt voor je reactie! Is het ook mogelijk om automatisch loon uit te zetten?

**Comment by Rammelkast** [comment]
Helaas nog niet, ik laat dit ticket wel even open staan als reminder dat ik dat moet toevoegen ;)

**Comment by sanderdevaan** [comment]
Wanneer is je verwachting dit af te hebben? Ik wil je eventueel ook een vergoeding geven om dit proces voor mij te versnellen.

**Comment by Rammelkast** [comment]
Haha, dat is niet nodig ;)
Ivm de warme dagen kan dit even duren, maar ik denk voor eind September.

[ Reminder genoteerd, issue gesloten ]
Mocht je nog een probleem ondervinden, dan kun je deze issue altijd heropenen.
